# -*- coding: utf-8 -*-
"""BirthdayCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYZ_bSGd0tpIYqqC9RScxrja6SQLRdAN

# Birthday Calculator
"""

from datetime import datetime, date

"""## Calculate age based on birthdate."""

def get_age(birthdate):
    today = date.today()
    age = today.year - birthdate.year
    # Adjust if birthday hasn't happened yet this year
    if (today.month, today.day) < (birthdate.month, birthdate.day):
        age -= 1
    return age

"""## Get the day name of the birthdate."""

def get_day_name(birthdate):
    return birthdate.strftime("%A")

"""## Validate and parse date string in dd-mm-yyyy format"""

def validate_date(date_str):
    parts = date_str.strip().split("-")

    # Must have exactly 3 parts
    if len(parts) != 3:
        return None

    # Check for negative values, symbols, or non-digit characters
    for part in parts:
        if not part.isdigit():
            return None

    day = int(parts[0])
    month = int(parts[1])
    year = int(parts[2])

    # Validate ranges
    if year < 1 or month < 1 or month > 12 or day < 1 or day > 31:
        return None

    # Try to create a valid date
    try:
        birthdate = date(year, month, day)
    except ValueError:
        return None

    # Make sure the date is not in the future
    if birthdate > date.today():
        return None

    return birthdate

def main():
    people = []

    print("=" * 40)
    print("     BIRTHDAY CALCULATOR")
    print("=" * 40)
    print("Enter name and birthdate (dd-mm-yyyy)")
    print("Type 'done' when finished.\n")

    # Accept unlimited number of people
    while True:
        name = input("Enter name (or 'done'): ").strip()
        if name.lower() == "done":
            break

        date_str = input(f"Enter birthdate for {name} (dd-mm-yyyy): ").strip()
        birthdate = validate_date(date_str)

        if birthdate is None:
            print(f"Invalid date, {name}\n")
            continue

        age = get_age(birthdate)
        day_name = get_day_name(birthdate)
        people.append({"name": name, "age": age, "day": day_name, "birthdate": birthdate})
        print()

    if len(people) == 0:
        print("No people were entered.")
        return

    # Print each person's info
    print("\n" + "=" * 40)
    for person in people:
        print(f"{person['name']} is {person['age']} years old and she/he was born on {person['day']}")

    # Oldest and youngest
    if len(people) == 1:
        print("There is no oldest or youngest person")
    else:
        oldest = max(people, key=lambda p: p["age"])
        youngest = min(people, key=lambda p: p["age"])
        print(f"The oldest one is {oldest['name']}")
        print(f"The youngest one is {youngest['name']}")

    print(f"Total People: {len(people)}")

    # --- Extra Questions ---

    # 1. Sort from oldest to youngest
    print("\n--- Sorted from oldest to youngest ---")
    sorted_people = sorted(people, key=lambda p: p["age"], reverse=True)
    for person in sorted_people:
        print(f"{person['name']} - {person['age']} years old")

    # 2. Print in reverse order
    print("\n--- Reverse input order ---")
    for person in reversed(people):
        print(f"{person['name']}, {person['birthdate'].strftime('%d-%m-%Y')}")

    # 3. People born on Sunday
    print("\n--- Born on Sunday ---")
    sunday_people = [p for p in people if p["day"] == "Sunday"]
    if sunday_people:
        for person in sunday_people:
            print(person["name"])
    else:
        print("No one was born on Sunday.")


if __name__ == "__main__":
    main()